title: Owen Sanborn
logo: /assets/img/logo.png
description: I'm Owen Sanborn, a molecular biologist dabbling in computational biology!
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
